#      _                 _     _             _                  _
#  ___| |_ __ _ _ __ ___| |__ (_)_ __       | |_ ___  _ __ ___ | |
# / __| __/ _` | '__/ __| '_ \| | '_ \      | __/ _ \| '_ ` _ \| |
# \__ \ || (_| | |  \__ \ | | | | |_) |  _  | || (_) | | | | | | |
# |___/\__\__,_|_|  |___/_| |_|_| .__/  (_)  \__\___/|_| |_| |_|_|
#                               |_|

add_newline = false
command_timeout = 999

[git_status]
format = "([$all_status$ahead_behind]($style) )"
style = "#DFDD51"

[line_break]
disabled = true

[cmd_duration]
disabled = false

[username]
style_user = "#81CE6B"
style_root = "bold #DFDD51"
format = "[$user]($style) in "
disabled = true
show_always = true

[package]
symbol = "ï£– "

[character]
success_symbol = "[â¯](bold #ffffff)"
error_symbol = "[â¯](bold #F8586E)"

[aws]
symbol = "îŒ½  "

[buf]
symbol = "ï’ "
format = "via [$symbol]($style)"

[c]
symbol = "î˜ "
format = "via [$symbol]($style)"

[conda]
symbol = "ï„Œ "

[dart]
symbol = "î˜ "
format = "via [$symbol]($style)"

[directory]
style = "#81CE6B"
read_only = " ï ½"

[docker_context]
symbol = "ïŒˆ "

[elixir]
symbol = "î‰µ "
format = "via [$symbol]($style)"

[elm]
symbol = "î˜¬ "
format = "via [$symbol]($style)"

[git_branch]
symbol = "ï˜ "
style = "#F8586E"

[golang]
symbol = "î˜§ "
format = "via [$symbol]($style)"

[haskell]
symbol = "î· "
format = "via [$symbol]($style)"

[hg_branch]
symbol = "ï˜ "

[java]
symbol = "î‰– "
format = "via [$symbol]($style)"

[julia]
symbol = "î˜¤ "
format = "via [$symbol]($style)"

[memory_usage]
symbol = "ï¡š "

[nim]
symbol = "ïš¤ "
format = "via [$symbol]($style)"

[nix_shell]
symbol = "ï‹œ "
format = "via [$symbol]($style)"

[nodejs]
symbol = "îœ˜ "
format = "via [$symbol]($style)"

[python]
symbol = "îˆµ "
format = "via [$symbol]($style)"

[spack]
symbol = "ğŸ…¢ "
format = "via [$symbol]($style)"

[rust]
symbol = "î¨ "
format = "via [$symbol]($style)"

[lua]
symbol = "î˜  "
format = 'via [$symbol]($style)'

[ruby]
symbol = "î‘ "
format = 'via [$symbol]($style)'
