#      _                 _     _             _                  _
#  ___| |_ __ _ _ __ ___| |__ (_)_ __       | |_ ___  _ __ ___ | |
# / __| __/ _` | '__/ __| '_ \| | '_ \      | __/ _ \| '_ ` _ \| |
# \__ \ || (_| | |  \__ \ | | | | |_) |  _  | || (_) | | | | | | |
# |___/\__\__,_|_|  |___/_| |_|_| .__/  (_)  \__\___/|_| |_| |_|_|
#                               |_|

add_newline = false

format = """
[â•­â”€â”€ ](bold white)$all\
[â•°â”€](bold white)$character"""

scan_timeout = 10

[line_break]
disabled = false

[cmd_duration]
style = "italic yellow"
format = "took [ï€— $duration]($style)"
disabled = false

[battery]
	disabled = true

[username]
style_user = "italic cyan"
format = "[î€ riceset]($style) at "
# style_root = "italic"
show_always = true

[package]
style = "italic 208"
symbol = "ï£– "

[character]
success_symbol = "[â¯](bold white)"
error_symbol = "[â¯](bold #red)"

[aws]
symbol = "îŒ½  "

[buf]
symbol = "ï’ "
format = "via [$symbol]($style)"

[c]
symbol = "î˜ "
format = "via [$symbol]($style)"

[conda]
symbol = "ï„Œ "

[dart]
symbol = "î˜ "
format = "via [$symbol]($style)"

[directory]
style = "italic green"
read_only = " ï ½ "
home_symbol = "ï€• "
format = "[$path]($style)[$read_only]($read_only_style) "
truncate_to_repo = true
repo_root_format = "[$read_only]($read_only_style)($style)[$repo_root]($style)[$path]($style) "
repo_root_style = ""

[docker_context]
style = "italic blue"
symbol = "ïŒˆ "

[elixir]
symbol = "î‰µ "
format = "via [$symbol]($style)"

[elm]
symbol = "î˜¬ "
format = "via [$symbol]($style)"

[git_branch]
symbol = "ï˜ "
style = "italic red"

[git_status]
style = "bold yellow"
ahead = "â–² ${count}"
behind = "â–¼ ${count}"
diverged = "â–² ${ahead_count} â–¼ ${behind_count}"

[golang]
symbol = "î˜§ "
format = "via [$symbol]($style)"

[haskell]
symbol = "î· "
format = "via [$symbol]($style)"

[hg_branch]
symbol = "ï˜ "

[java]
symbol = "î‰– "
format = "via [$symbol]($style)"

[julia]
symbol = "î˜¤ "
format = "via [$symbol]($style)"

[nim]
symbol = "ïš¤ "
format = "via [$symbol]($style)"

[nix_shell]
symbol = "ï‹œ "
format = "via [$symbol]($style)"

[nodejs]
symbol = "îœ˜ "
format = "via [$symbol]($style)"

[python]
symbol = "îˆµ "
format = "via [$symbol]($style)"

[spack]
symbol = "ğŸ…¢ "
format = "via [$symbol]($style)"

[rust]
symbol = "î¨ "
format = "via [$symbol]($style)"

[lua]
symbol = "î˜  "
format = 'via [$symbol]($style)'

[ruby]
symbol = "î‘ "
format = 'via [$symbol]($style)'
