add_newline = false

format = """
[â•­â”€â”€ ](bold)$all\
[â•°â”€](bold)$character"""

scan_timeout = 10

[line_break]
disabled = false

[cmd_duration]
style = "italic yellow"
format = "took [ï€— $duration]($style)"
disabled = true

[battery]
	disabled = true

[username]
style_user = "italic yellow"
format = "[riceset]($style) at "
# style_root = "italic"
show_always = true

[package]
style = "italic 208"
symbol = "ï£– "
disabled = true

[character]
success_symbol = "[â¯](bold)"
error_symbol = "[â¯](bold #red)"

[aws]
symbol = "îŒ½  "
disabled = true

[buf]
symbol = "ï’ "
format = "via [$symbol]($style)"
disabled = true

[c]
symbol = "î˜ "
format = "via [$symbol]($style)"
disabled = true

[conda]
symbol = "ï„Œ "
disabled = true

[dart]
symbol = "î˜ "
format = "via [$symbol]($style)"
disabled = true

[directory]
style = "italic green"
read_only = " ï ½ "
# home_symbol = "ï€• "
format = "[$path]($style)[$read_only]($read_only_style) "
truncate_to_repo = true
repo_root_format = "[$read_only]($read_only_style)($style)[$repo_root]($style)[$path]($style) "
repo_root_style = ""
truncation_length = 3
use_logical_path = false

[docker_context]
style = "italic blue"
symbol = "ïŒˆ "

[elixir]
symbol = "î‰µ "
format = "via [$symbol]($style)"
disabled = true

[elm]
symbol = "î˜¬ "
format = "via [$symbol]($style)"
disabled = true

[git_branch]
symbol = "ï˜ "
style = "italic red"

[git_status]
style = "bold red"
ahead = "â–² ${count}"
behind = "â–¼ ${count}"
diverged = "â–² ${ahead_count} â–¼ ${behind_count}"

[golang]
symbol = "î˜§ "
format = "via [$symbol]($style)"
disabled = true

[haskell]
symbol = "î· "
format = "via [$symbol]($style)"
disabled = true

[hg_branch]
symbol = "ï˜ "

[java]
symbol = "î‰– "
format = "via [$symbol]($style)"
disabled = true

[julia]
symbol = "î˜¤ "
format = "via [$symbol]($style)"
disabled = true

[nim]
symbol = "ïš¤ "
disabled = true
format = "via [$symbol]($style)"

[nix_shell]
symbol = "ï‹œ "
format = "via [$symbol]($style)"
disabled = true

[nodejs]
symbol = "îœ˜ "
format = "via [$symbol]($style)"
disabled = true

[python]
symbol = "îˆµ "
format = "via [$symbol]($style)"
disabled = true

[spack]
symbol = "ğŸ…¢ "
format = "via [$symbol]($style)"
disabled = true

[rust]
symbol = "î¨ "
format = "via [$symbol]($style)"
disabled = true

[lua]
symbol = "î˜  "
format = 'via [$symbol]($style)'
disabled = true

[ruby]
symbol = "î‘ "
format = 'via [$symbol]($style)'
disabled = true

[swift]
disabled = true
